language: java
sudo: false
jdk:
  - oraclejdk8
  - openjdk8
  - oraclejdk9
  - oraclejdk10
install: ./gradlew   assemble --stacktrace
script:
  - ./gradlew clean build -PuseSpotbugs=true --stacktrace
  - ./mvnw verify
notifications:
  email: false
branches:
  only:
    - master
    - develop
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/